// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbo57lHEx0rYOhjYJU_JbhbNjT82lXCG4',
    appId: '1:659649077948:android:67dd0ac09c4111b9e1a6b9',
    messagingSenderId: '659649077948',
    projectId: 'saathi-9c122',
    storageBucket: 'saathi-9c122.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFdNATp0qLdESgfoql8fyZtxqL7WCH7tE',
    appId: '1:659649077948:ios:2db815e36f6a897be1a6b9',
    messagingSenderId: '659649077948',
    projectId: 'saathi-9c122',
    storageBucket: 'saathi-9c122.firebasestorage.app',
    androidClientId: '659649077948-3vj9osfc50p73etgscc1fanihdt9t4ob.apps.googleusercontent.com',
    iosClientId: '659649077948-7vnfnhcf5a6viut74j5r4kvs6cdv9otm.apps.googleusercontent.com',
    iosBundleId: 'com.example.genAi',
  );
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6DXwvEyin_sgMn60qtjR8t_4FdaSEkOQ',
    appId: '1:659649077948:web:aa10686b1562ce0be1a6b9',
    messagingSenderId: '659649077948',
    projectId: 'saathi-9c122',
    authDomain: 'saathi-9c122.firebaseapp.com',
    storageBucket: 'saathi-9c122.firebasestorage.app',
    measurementId: 'G-F4YYCLS9CP',
  );
}
